// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB99opLxMalM5ZDQgfrKnEsl8L5j6OzrKI',
    appId: '1:566699516882:web:541098e7314ad137a7de0b',
    messagingSenderId: '566699516882',
    projectId: 'penyaciclista-64b07',
    authDomain: 'penyaciclista-64b07.firebaseapp.com',
    storageBucket: 'penyaciclista-64b07.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcA9dkMrqLVutDJGLUlHyuEwbNsId-IjE',
    appId: '1:566699516882:android:11c38b7f51d97e22a7de0b',
    messagingSenderId: '566699516882',
    projectId: 'penyaciclista-64b07',
    storageBucket: 'penyaciclista-64b07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDersD0vNLLLU7MUHj_KOzgQu6Jk1Jxmus',
    appId: '1:566699516882:ios:0169892d07ef37c0a7de0b',
    messagingSenderId: '566699516882',
    projectId: 'penyaciclista-64b07',
    storageBucket: 'penyaciclista-64b07.appspot.com',
    iosClientId: '566699516882-9o52k32hj5ofp6beelij9mqadnta28s5.apps.googleusercontent.com',
    iosBundleId: 'com.example.penyaCiclista',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDersD0vNLLLU7MUHj_KOzgQu6Jk1Jxmus',
    appId: '1:566699516882:ios:48531f748430cd92a7de0b',
    messagingSenderId: '566699516882',
    projectId: 'penyaciclista-64b07',
    storageBucket: 'penyaciclista-64b07.appspot.com',
    iosClientId: '566699516882-6r4tsjl4e0d6t8d28121bjdvhch56dv0.apps.googleusercontent.com',
    iosBundleId: 'com.example.penyaCiclista.RunnerTests',
  );
}
